### ISSUE TITLE
beim reload auf room/ROOM_ID ist die id nicht mehr da und die song list wird nicht geladen

### ISSUE THREAD

**Issue by timunkulus** [andreasellw/scalable_client#10]
Evlt aus der URL ziehen?

**Comment by stephh93** [comment]
müsste eig relativ simple über den router gehen

**Comment by stephh93** [comment]
Die beiden renderPlaylist/admin routen haben ja die infos

**Comment by timunkulus** [comment]
beim admin würde ich es nicht reinmachen, damit man als normaler gast nicht üben den link auf die admin page gehen kann!
