### ISSUE TITLE
Leere Playlists

### ISSUE THREAD

**Issue by stephh93** [andreasellw/scalable_client#13]
Wie handhaben wir leere Playlists? Aktuell ist der Player dann einfach leer

**Comment by andreasellw** [comment]
@griase94 @timunkulus

**Comment by stephh93** [comment]
also der leere Player macht probleme wenn dann ein neues lied geladen werden sollte - ich bin für einen platzhalter

**Comment by stephh93** [comment]
wie wärs mit ner zufallswiedergabe bereits gespielter?

**Comment by stephh93** [comment]
Ok habs jetzt so umgesetzt: am anfang kommt ein kurzes startup video (aktuell 7s):
- dann wird gewartet bis Daten gefunden werden 
- wurden alle playlist song gespielt wird ein random aus den gespielten genommen

**Comment by timunkulus** [comment]
finde ich nice so
