### ISSUE TITLE
Möglichkeit, als Admin Songs aus der Playlist zu löschen 

### ISSUE THREAD

**Issue by timunkulus** [andreasellw/scalable_client#14]
Backend Route dazu existiert schon

**Comment by andreasellw** [comment]
Kann mit #21 kombiniert werden.
Wie findet man heraus ob man auf der Admin Page ist? Darüber könnte man die zwei Hacken vom VoteComp einfach dann ausblenden und daneben ein (x) Button setzen, welcher den Löschvorgang abschickt.

**Comment by stephh93** [comment]
"Wie findet man heraus ob man auf der Admin Page ist" - hm weis nicht ob das geht, notfalls kann man den Probs der PlaylistBox ja ein Flag geben, wär ja dann auch tatsächlich eine Property

**Comment by andreasellw** [comment]
@stephh93 alles klar - danke. jo dann lös ich das so.
