### ISSUE TITLE
Playlist managen

### ISSUE THREAD

**Issue by timunkulus** [andreasellw/scalable_client#15]
wenn ein song abgespielt nicht mehr in vote liste anzeigen
querien, wenn song zu ende

**Comment by andreasellw** [comment]
& Delete Button (für den Adminbereich)

**Comment by andreasellw** [comment]
@timunkulus ? Also in der Vote Liste werden nur noch Lieder mit Status QUEUE angezeigt.
Was soll hier noch geschehen?
