### ISSUE TITLE
Repeating song

### ISSUE THREAD

**Issue by andreasellw** [andreasellw/scalable_client#28]
Bei mir will ein Song nicht mehr aufhören zu spielen. Ich hab den Song bis kurz vors Ende vor gespult, aber gleich im Anschluss kommt der gleiche Song erneut.
Glaube das liegt daran, wenn der aktuell spielende Song genau gleich viele Votes hat wie der potentiell nächste Song. Siehe Video WhatsApp.

**Comment by stephh93** [comment]
Jo hab ich auch gerade gefunden - liegt daran dass ich das in der Annahme entwickelt hab das ein gespielter song nicht mehr in der playlist liegt - ich sitz dran

**Comment by andreasellw** [comment]
Du kannst die Liste einfach filtern wie ich es schon gemacht haben bei AlreadyPlayedComponent.

**Comment by stephh93** [comment]
Jop bin gerade am testen

**Comment by stephh93** [comment]
Ah das geht noch leichter mit: list.filter(s => s.playState.equals("QUEUE"))

**Comment by stephh93** [comment]
Aber der Youtube player macht probleme wenn er mal leer ist ... da muss man nochmal ran

**Comment by stephh93** [comment]
hab jetzt ein hässliches rauschen rein

**Comment by stephh93** [comment]
als placeholder
