### ISSUE TITLE
Lieder werden am Anfang nicht abgespielt

### ISSUE THREAD

**Issue by andreasellw** [andreasellw/scalable_client#33]
Nachdem man einen neuen Room angelegt hat und das kurze Gamecube Intro Video abgespielt wurde wird ja nichts mehr abgespielt. Wenn man dann die Playlist befüllt startet der Videoplayer nicht automatisch, sondern man muss noch mal auf Replay vom Gamecube Video gehen.

**Comment by stephh93** [comment]
hab da wohl eine einfache abfrage iwo verkackt - mach mich im zug dran
